run: # https://golangci-lint.run/usage/configuration/#run-configuration
  go: '1.22'
  timeout: 3m

linters-settings: # https://golangci-lint.run/usage/configuration/#linters-settings-configuration
  gocyclo:
    min-complexity: 36
  gci: # https://golangci-lint.run/usage/linters/#gci
    sections:
      - standard
      - default
      - localmodule
    custom-order: true
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern: 'interface{}'
        replacement: 'any'
      - pattern: 'a[b:len(a)]'
        replacement: 'a[b:]'
  revive:
    enable-all-rules: false
    rules:
      - name: empty-lines
      - name: use-any
      - name: struct-tag
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-naming
      - name: exported
        disabled: true
      - name: if-return
      - name: increment-decrement
      - name: var-declaration
      - name: package-comments
        disabled: true
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: superfluous-else
      - name: unused-parameter
        disabled: true
      - name: unreachable-code
      - name: redefines-builtin-id

linters: # https://golangci-lint.run/usage/linters/
  disable-all: true
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - copyloopvar
    - dogsled
    - dupl
    - errcheck
    - fatcontext
    - funlen
    - gci
    - gocyclo
    - gocritic
    - gofmt
    - goheader
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - prealloc
    - misspell
    - mirror
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unused
    - whitespace
    - revive
    - protogetter
    - tagalign

issues: # https://golangci-lint.run/usage/configuration/#issues-configuration
  exclude-rules:
    - path: _test\.go
      linters:
        - dupl
        - funlen
        - gosec
        - gocritic
        - errcheck